# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

jobs:
- job: OSX
  pool:
    vmImage: 'xcode9-macos10.13'
  steps:
    - task: Bash@3
      inputs:
        targetType: 'filePath'
        filePath: 'build.sh'
        arguments: '-configuration $(buildConfiguration) -target CiNonWin -framework netcoreapp2.1'
        failOnStderr: true
      displayName: 'Build'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '*.trx'
        searchFolder: '$(Build.SourcesDirectory)/artifacts/tests'
      displayName: 'Publish Test results'

- job: Ubuntu
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - task: Bash@3
      inputs:
        targetType: 'filePath'
        filePath: 'build.sh'
        arguments: '-configuration $(buildConfiguration) -target CiNonWin -framework netcoreapp2.1'
        failOnStderr: true
      displayName: 'Build'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '*.trx'
        searchFolder: '$(Build.SourcesDirectory)/artifacts/tests'
      displayName: 'Publish Test results'

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
    - task: PowerShell@2
      inputs:
        targetType: 'filePath'
        filePath: 'build.ps1'
        arguments: '-configuration $(buildConfiguration) -target Ci'
        failOnStderr: true
      displayName: 'Build'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '*.trx'
        searchFolder: '$(Build.SourcesDirectory)/artifacts/tests'
      displayName: 'Publish Test results'
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.SourcesDirectory)/artifacts/nuget'
        artifactName: 'Nuget'
      displayName: 'Publish Artifacts'

trigger:
- master
- develop
- release/*

variables:
  buildConfiguration: 'Release'

