# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

strategy:
  matrix:
    windows:
      imageName: 'vs2017-win2016'

trigger:
- master
- develop
- release/*

pool:
  vmImage: $(imageName)

variables:
  buildConfiguration: 'Release'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: 'build.ps1'
    arguments: '-configuration $(buildConfiguration) -target CI'
    failOnStderr: true
  displayName: 'Build'
- task: PublishTestResults@2
  inputs:
   testResultsFormat: 'VSTest'
   testResultsFiles: '*.trx'
   searchFolder: 'artifacts'
  displayName: 'Publish Test results'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'artifacts'
    artifactName: 'drop'
    targetPath: '*.nupkg' 
  displayName: 'Publish Artifacts'